<?php

namespace App\Repository;

/**
 * PermisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisoRepository extends \Doctrine\ORM\EntityRepository
{
}
