#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#homepage:
#  path: /{_locale}
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#  requirements:
#    _locale: '%app_locales%'
#  defaults:
#    template: default/homepage.html.twig
#    _locale: '%locale%'

#app:
#  resource: '@App/Controller/'
#  type: annotation


login_check:
  path:     /login_check
